services:
  influxdb:
    image: influxdb:2.1-alpine
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/db:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=/run/secrets/db_user
      - DOCKER_INFLUXDB_INIT_PASSWORD=/run/secrets/db_pass
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=scrutiny
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=/run/secrets/db_token
    secrets:
      - db_user
      - db_pass
      - db_token

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./scrutiny/config:/opt/scrutiny/config
    environment:
      - SCRUTINY_WEB_INFLUXDB_HOST=influxdb
      - SCRUTINY_WEB_INFLUXDB_PORT=8086
      - SCRUTINY_WEB_INFLUXDB_TOKEN=/run/secrets/db_token
      - SCRUTINY_WEB_INFLUXDB_ORG=homelab
      - SCRUTINY_WEB_INFLUXDB_BUCKET=scrutiny
      # Optional but highly recommended to notify you in case of a problem
      #- SCRUTINY_NOTIFY_URLS=/run/secrets/telegram_token
    secrets:
      - db_token
      - telegram_token
    depends_on:
      - influxdb

secrets:
  db_user:
    file: ./secrets/db_user.secret
  db_pass:
    file: ./secrets/db_pass.secret
  db_token:
    file: ./secrets/db_token.secret
  telegram_token:
    file: ./secrets/telegram_token.secret