services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    ports:
      - 8123:8123
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pb/dockerData/homeAssistant/config:/config
    privileged: true
    #network_mode: host
    networks:
      proxy:
networks:
  proxy:
    external: true