services:
  trilium:
    image: zadam/trilium
    container_name: trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    ports:
      - 8081:8080
    volumes:
      - ./data:/home/node/trilium-data