services:
  motioneye:
    image: ccrisan/motioneye:master-amd64
    container_name: motioneye
    hostname: motioneye
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8765:8765
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/motioneye
      - ./lib:/var/lib/motioneye