services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./config:/config
    ports:
      - 8088:80
      - 4433:443
    networks:
      proxy:
networks:
  proxy:
    external: true